name: Check PR Branch Source

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  cicd_test:
    name: check_merge_main_from_develop
    runs-on: ubuntu-latest
    steps:
      - name: Check if the PR targets main from develop
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" == "main" ] && [ "${{ github.event.pull_request.head.ref }}" != "develop" ]; then
            echo "Pull request not from develop to main branch"
            exit 1
          else
            echo "Pull request from develop to main branch"
          fi